# Generated by Django 5.0.2 on 2024-02-12 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Adresse', models.CharField(max_length=50)),
                ('Date_Recruitment', models.DateField()),
                ('Date_Detach', models.DateField()),
                ('Situation_Famillial', models.CharField(max_length=30)),
                ('Nbr_Enfant', models.IntegerField()),
                ('ID_Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointage.station')),
            ],
        ),
        migrations.CreateModel(
            name='Chef_Station',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Station', models.CharField(max_length=40, unique=True)),
                ('Password', models.CharField(max_length=40)),
                ('ID_Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointage.station')),
            ],
        ),
    ]
