# Generated by Django 5.0.2 on 2024-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0003_rename_situation_famillial_employe_fonction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='Sheet_ID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
