# Generated by Django 5.0.2 on 2024-02-16 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0004_employe_sheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='ID_Station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pointage.chef_station'),
        ),
    ]
