# Generated by Django 5.0.2 on 2024-02-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0006_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
