# Generated by Django 5.0.2 on 2024-02-20 16:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0007_alter_employe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Station', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='chef_station',
            old_name='ID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='chef_station',
            name='Nom_Station',
        ),
        migrations.RemoveField(
            model_name='chef_station',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='ID_Station',
        ),
        migrations.AlterField(
            model_name='employe',
            name='Date_Recrutement',
            field=models.DateField(default=datetime.date(2024, 2, 20), null=True),
        ),
        migrations.AddField(
            model_name='chef_station',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pointage.station'),
        ),
        migrations.AddField(
            model_name='employe',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pointage.station'),
        ),
    ]
