# Generated by Django 5.0.2 on 2024-02-22 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0012_code_alter_employe_date_recrutement_code_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_employe',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 22, 7, 57, 38, 29011)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Date_Recrutement',
            field=models.DateField(default=datetime.date(2024, 2, 22)),
        ),
    ]
