# Generated by Django 5.0.2 on 2024-02-22 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0013_alter_code_employe_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_employe',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 22, 10, 34, 18, 689124)),
        ),
    ]
