# Generated by Django 5.0.2 on 2024-02-22 09:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0014_alter_code_employe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_employe',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 22, 10, 59, 31, 670697)),
        ),
        migrations.AlterField(
            model_name='code_employe',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_emp', to='pointage.employe'),
        ),
    ]
